InventoryTracker/Models/Asset.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryTracker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Asset
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Asset()
        {
            this.PropertyValues = new HashSet<PropertyValue>();
        }
    
        public int AssetID { get; set; }
        public int AssetTypeID { get; set; }
        public System.DateTime DateAdded { get; set; }
        public System.DateTime DateLastModified { get; set; }
    
        public virtual AssetType AssetType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PropertyValue> PropertyValues { get; set; }
    }
}

InventoryTracker/Models/AssetType.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryTracker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssetType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AssetType()
        {
            this.Assets = new HashSet<Asset>();
            this.Properties = new HashSet<Property>();
        }
    
        public int AssetTypeID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public byte Tracked { get; set; }
        public byte Active { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Asset> Assets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Property> Properties { get; set; }
    }
}

InventoryTracker/Models/ViewModels/AssetViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace InventoryTracker.Models.ViewModels
{
    public class AssetViewModel
    {
        public int AssetID { get; set; }
        public AssetTypeViewModel AssetType { get; set; }
        public int AssetTypeID { get; set; }
        public string DateAdded { get; set; }
        public string DateLastModified { get; set; }

        public AssetViewModel() { }

        public AssetViewModel(Asset entityAsset)
        {
            this.AssetID = entityAsset.AssetID;
            this.AssetType = new AssetTypeViewModel(entityAsset.AssetType);
            this.AssetTypeID = entityAsset.AssetTypeID;
            this.DateAdded = entityAsset.DateAdded.ToString("MM/dd/yy H:mm");
            this.DateLastModified = entityAsset.DateLastModified.ToString("MM/dd/yy H:mm");
            // Set the values for the properties
            var i = 0;
            foreach (PropertyViewModel prop in this.AssetType.Properties)
            {
                this.AssetType.Properties[i].Value = this.getPropertyValue(prop, entityAsset);
                i++;
            }
        }

        private string getPropertyValue(PropertyViewModel prop, Asset entityAsset)
        {
            foreach (PropertyValue propValue in entityAsset.PropertyValues)
            {
                if (propValue.PropertyID == prop.PropertyID)
                {
                    return propValue.Value;
                }
            }
            return "";
        }
    }
}

InventoryTracker/Controllers/AssetController.cs
using LumenWorks.Framework.IO.Csv;
using InventoryTracker.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;
using System.Net.Mail;
using InventoryTracker.Models.ViewModels;

namespace InventoryTracker.Controllers
{
    public class AssetController : Controller
    {
        private InventoryTrackerEntities db = new InventoryTrackerEntities();

        // GET: Asset
        public ActionResult Index()
        {
            return View("Browse");
        }
        
        public ActionResult CreateFile(int id = 0)
        {
            //Create CSV File based upon user asset selection

            //https://stackoverflow.com/questions/1375486/how-to-create-file-and-return-it-via-fileresult-in-asp-net-mvc
            //https://www.codeproject.com/Articles/325103/MVC-Grid-to-Excel-file-download


            //Convert the rendering of the gridview to a string representation 
            StringWriter sw = new StringWriter();

            AssetType findTheAssetType = db.AssetTypes.Find(id);
            //******** building a comma seperated string by going thru properties
            foreach (Property prop in findTheAssetType.Properties)
            {
                sw.Write(prop.Name + ",");
            }
     
            //Create a response stream to create and write the Excel file

            this.HttpContext.Response.Clear();
            this.HttpContext.Response.AddHeader("content-disposition", "attachment;filename=" + findTheAssetType.Name +".csv");
            this.HttpContext.Response.Charset = "";
            this.HttpContext.Response.Cache.SetCacheability(HttpCacheability.NoCache);
            this.HttpContext.Response.ContentType = "application/vnd.ms-excel";

            //Open a memory stream that you can use to write back to the response
            byte[] byteArray = System.Text.Encoding.ASCII.GetBytes(sw.ToString());
            MemoryStream s = new MemoryStream(byteArray);
            StreamReader sr = new StreamReader(s, System.Text.Encoding.ASCII);

            //Write the stream back to the response
            this.HttpContext.Response.Write(sr.ReadToEnd());
            this.HttpContext.Response.End();

            return View("");
        }

        // GET: Asset/Browse
        public ActionResult Browse(int id = 0)
        {
            // Gather a list of AssetTypes to fill in the drop down of AssetTypes to browse
            ViewBag.assetTypes = db.AssetTypes.Where(assetType => assetType.Active == 1).ToList();

            // If an AssetTypeID was provided, gather the AssetType and Assets associated with it
            if (id != 0)
            {
                ViewBag.assetTypeToBrowse = db.AssetTypes.Find(id);
                IEnumerable<Asset> dbAssets = db.Assets.Where(asset => asset.AssetTypeID == id).ToList();
                AssetViewModel[] assets = new AssetViewModel[dbAssets.Count()];
                for (var i = 0; i < dbAssets.Count(); i++)
                {
                    assets[i] = new AssetViewModel(dbAssets.ElementAt(i));
                }
                ViewBag.assets = assets;
            }
            else
            {
                ViewBag.assetTypeToBrowse = null;
                ViewBag.assets = null;
            }

            return View();
        }

        // GET: Asset/Edit
        public ActionResult Edit(int id, int assetTypeID = 0)
		{
            ViewBag.assetID = id;
            ViewBag.assetTypeID = assetTypeID;
            return View();
		}

        // Get an array of DropDowns from the DB
        private DropDownBare[] getDropDowns()
        {
            List<DropDownBare> dropDowns = new List<DropDownBare>();
            List<DropDown> dbDropDowns = db.DropDowns.ToList();
            foreach (DropDown dd in dbDropDowns)
            {
                dropDowns.Add(dd.getDropDownBare());
            }
            return dropDowns.ToArray();
        }

        public ActionResult View(int id)
        {
            AssetViewModel asset = new AssetViewModel(db.Assets.Find(id));
            return View(asset);
        }

        public ActionResult BulkImport()
        {
            return View();
        }

        public ActionResult Upload(int id)
        {
            //This gets called from the javascript.
            //https://stackoverflow.com/questions/34223736/maintaining-viewbag-values-while-posting-data
            
            //put assetID in viewbag so it can be passed onto the csv upload.
            ViewBag.AssetIdForUpload = id;
            return View();
        }

        
        [HttpPost]
        [ValidateAntiForgeryToken]
        //The assetID comes from the hidden field on the upload.cshtml
        public ActionResult Upload(HttpPostedFileBase upload, int assetId=0)
        {
            if (ModelState.IsValid)
            {
                if (upload != null && upload.ContentLength > 0)
                {

                    if (upload.FileName.EndsWith(".csv"))
                    {
                        Stream stream = upload.InputStream;
                        DataTable csvTable = new DataTable();
                        using (CsvReader csvReader =
                            new CsvReader(new StreamReader(stream), true))
                        {
                            // loads the csv file in a datatable
                            csvTable.Load(csvReader);

                            // Make sure that the csv has the right columns in it this needs to be dynamic based on the asset type
                           
                            if (assetId == 0)
                                {

                                ViewBag.ErrorMessage = "Error... Asset id not specified";
                                return View("");
                                                                
                            }

                            ViewBag.ErrorMessage = "";
                            //loop thru table
                            foreach (DataRow row in csvTable.Rows)
                            {
                                // Get The asset type id
                                int assetTypeId = assetId;

                                // Find the asset type according to the id ****
                                
                                AssetType findTheAssetType = db.AssetTypes.Find(assetTypeId);

                                // Create a new asset and give it the assetTypeId you just found
                                Asset newAsset = new Asset()
                                {
                                    AssetTypeID = findTheAssetType.AssetTypeID,
                                    DateAdded = DateTime.Now,
                                    DateLastModified = DateTime.Now
                            };

                                //Add the asset, save the changes so we can get the id to use for saving property values*****
                                Asset addedAsset = db.Assets.Add(newAsset);                               
                                db.SaveChanges();

                                // loop thru the rest of the columns to get the values
                                for (int col=0; col < csvTable.Columns.Count; col++)
                                {
                                    //get the column name and value
                                    string columnName = csvTable.Columns[col].ToString();
                                    string columnValue = row[col].ToString();

                                    // Find the corresponding Property by looping thru all until we find it ****
                                    //grab assetType and iterte through to find name.
                                    foreach (Property propertyItem in findTheAssetType.Properties)
                                    {
                                        //System.Diagnostics.Debugger.Break();

                                        //if the column name matches the property name then create a new property value.
                                        if (propertyItem.Name.ToLower() == columnName.Trim().ToLower())
                                        {
                                            // found the matching property, now create a new value
                                            PropertyValue newPropertyValue = new PropertyValue();

                                            //give the new property the propertyID and the assetID from above
                                            newPropertyValue.PropertyID = propertyItem.PropertyID;
                                            newPropertyValue.AssetID = addedAsset.AssetID;
                                            newPropertyValue.Value = columnValue;

                                            //add the new property to the properties
                                            db.PropertyValues.Add(newPropertyValue);
                                            break; // exit the loop
                                        }
                                    }

                                    // Save the newly added property value
                                    db.SaveChanges();
                                }
                            }
                        }
                        
                        return View(csvTable);
                    }
                    else
                    {
                        ModelState.AddModelError("File", "This file format is not supported");
                        return View();
                    }
                }
                else
                {
                    ModelState.AddModelError("File", "Please Upload Your file");
                }
            }
            return View();
        }

InventoryTracker/Views/Asset/Browse.cshtml
@{
    ViewBag.Title = "Browse Assets";
}
@section Scripts
    {
        <script src="@Url.Content("~/Scripts/Asset/Browse.js")"></script>
        <script src="@Url.Content("~/Scripts/DataTables/datatables.js")"></script>
        <script src="@Url.Content("~/Scripts/Common/ConfirmModal.js")"></script>
        <script src="@Url.Content("~/Scripts/Common/LoadingModal.js")"></script>
    }

@section Styles {
    <link href="@Url.Content("~/Scripts/DataTables/datatables.css")" rel="stylesheet" type="text/css" />
}

<h1>Browse Assets</h1>
<label>Asset Types:</label>
<select id="assetType" class="form-control" onchange="window.location = '/Asset/Browse/' + this.value">
    <option value="0">--Select--</option>
    @if (ViewBag.assetTypeToBrowse != null)
    {
        foreach (var item in ViewBag.assetTypes)
        {
            <option @(item.AssetTypeID == ViewBag.assetTypeToBrowse.AssetTypeID ? "selected" : "") value="@item.AssetTypeID">@item.Name</option>
        }
    }else
    {
        foreach (var item in ViewBag.assetTypes)
        {
            <option value="@item.AssetTypeID">@item.Name</option>
        }
    }
</select>
<hr />
@if (ViewBag.assetTypeToBrowse != null)
{
    
    <a onclick="createNewAsset()" class="btn">Create New</a>
    <a onclick="createNewCsvFile()" class="btn">Create CSV</a>
    <!-- Upload csv  go to upload javascript function -->         
    <a onclick = "uploadCsvFile()" class="btn">Upload a CSV File</a>

    <hr />
}
<!--Begin Assets Table-->
<table id="assetsTable">
    <thead>
        <tr>
            <th>Options</th>
            @if (ViewBag.assetTypeToBrowse != null)
            {
                foreach (var prop in ViewBag.assetTypeToBrowse.Properties)
                {
                    if (prop.Active == 1)
                    {
                        <th>@prop.Name</th>
                    }
                }
            }
		</tr>
	</thead>
	<tbody>
        @if (ViewBag.assets != null)
        {
            foreach (var asset in ViewBag.assets)
            {
                if (asset.AssetTypeID == ViewBag.assetTypeToBrowse.AssetTypeID)
                {
                    <tr>
                        <td>
                            <a href="/Asset/Edit/@asset.AssetID">Edit</a> |
                            <a href="/Asset/View/@asset.AssetID">View</a> |
                            <a class="clickable" onclick="deleteAsset(@asset.AssetID)">Delete</a>
                        </td>
                        @foreach (var prop in asset.AssetType.Properties)
                        {
                            if (prop.Active)
                            {
                                <td>
                                    @if (@prop.Value == "")
                                {
                                        <div class="center">--</div>
                                    }
                                    else
                                    {
                                        @prop.Value
                                    }
                                </td>
                            }
                        }
                    </tr>
                }
            }
        }
	</tbody>
</table>
<!--End Assets Table-->

InventoryTracker/Views/Asset/Edit.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}


@section Scripts
{
    <script src="@Url.Content("~/Scripts/Asset/Edit.js")"></script>
    <script src="@Url.Content("~/Scripts/Common/DropDown.js")"></script>
    <script src="@Url.Content("~/Scripts/Common/DropDownHelper.js")"></script>
    <script src="@Url.Content("~/Scripts/Common/Asset.js")"></script>
    <script src="@Url.Content("~/Scripts/Common/AssetType.js")"></script>
    <script src="@Url.Content("~/Scripts/Common/Property.js")"></script>
    <script src="@Url.Content("~/Scripts/Common/LoadingModal.js")"></script>
}
<div>
    <h3><span id="type"></span> Asset:</h3>
    @if (@ViewBag.id != 0)
    {
        <b>Created:</b> <span id="dateAdded"></span> <b>Last Modified:</b> <span id="dateLastModified"></span>
    }
</div>
<hr />
<div id="propertiesDiv" class="container"></div>
<hr />
<button onclick="save()" class="btn">Save</button>
<button onclick="window.location = '/Asset/Browse/' + asset.AssetType.id" class="btn">Cancel</button>
<script>
    var assetId = @ViewBag.assetID;
    var assetTypeId = @ViewBag.assetTypeID;
</script>

InventoryTracker/Views/Asset/Upload.cshtml
<!--installed lumenWorksCsvReader to read the file
    http://techbrij.com/read-csv-asp-net-mvc-file-upload


    -->
@{
    ViewBag.Title = "BulkImport";
}

@model System.Data.DataTable
@using System.Data;

<h2>Upload File</h2>

@using (Html.BeginForm("Upload","Asset", null, FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary()

    <!--need to save the assetID in a hidden field so when upload method is called the assetID can be passed in-->
    <input type="hidden" value="@ViewBag.AssetIdForUpload" name="assetId" />

    <div class="form-group">
        <input type="file" id="dataFile" name="upload" />
    </div>

    <div class="form-group">
        <input type="submit" value="Upload" class="btn btn-default" />
    </div>

    <!-- Display errors if there are any in the veiw bag -->
    <p></p>
    <div>@ViewBag.ErrorMessage</div>
    if (Model != null)
    {
        <div>Data From CSV File</div>
        <div></div>
        <table>
            <thead>
                <tr>
                    @foreach (DataColumn col in Model.Columns)
                    {
                        <th>@col.ColumnName</th>
                    }
                </tr>
            </thead>
            <tbody>
                @foreach (DataRow row in Model.Rows)
                {
                    <tr>
                        @foreach (DataColumn col in Model.Columns)
                        {
                            <td>@row[col.ColumnName]</td>
                        }
                    </tr>
                }
            </tbody>
        </table>
        <br />
    
    }
}

InventoryTracker/Views/Asset/View.cshtml
@model InventoryTracker.Models.ViewModels.AssetViewModel

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div>
    <div id="propertiesDiv" class="container">
        @foreach (var property in Model.AssetType.Properties)
        {
            if (property.Active)
            {
                <div class="row">
                    <div class="col-sm-3">
                        <h4>@Html.DisplayFor(modelItem => property.Name)</h4>
                    </div>
                    <div class="col-sm-3">
                        @Html.DisplayFor(modelItem => property.Value)
                    </div>
                    <div class="col-sm-6">
                    </div>
                </div>
            }
        }
    </div>
</div>